name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: mypomodoro
            asset_name: mypomodoro-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: mypomodoro.exe
            asset_name: mypomodoro-windows-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: mypomodoro
            asset_name: mypomodoro-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: mypomodoro
            asset_name: mypomodoro-macos-aarch64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev

    - name: Install cargo-bundle
      run: cargo install cargo-bundle

    - name: Build Windows
      if: matrix.os == 'windows-latest'
      run: ./build.bat

    - name: Build macOS
      if: matrix.os == 'macos-latest'
      run: ./build.sh --macos

    - name: Build Linux
      if: matrix.os == 'ubuntu-latest'
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/release/${{ matrix.artifact_name }}

    - name: Upload macOS artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/release/bundle/osx/MyPomodoro.app/

    - name: Upload Linux artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./artifacts/mypomodoro-linux-x86_64/mypomodoro
          ./artifacts/mypomodoro-windows-x86_64/mypomodoro.exe
          ./artifacts/mypomodoro-macos-x86_64/*
          ./artifacts/mypomodoro-macos-aarch64/*